import Aiur.Scalar.AST
import Aiur.Scalar.Typecheck
import Aiur.Scalar.Eval
import Aiur.Scalar.Semantics
import Aiur.Scalar.Circuit
import Aiur.Scalar.Correctness
import Aiur.Scalar.MemoCompleteness
import Aiur.Scalar.MemoSoundness
import Aiur.Scalar.EvalCorrectness
import Aiur.Scalar.Frontend
